# Generated by Django 2.2.19 on 2022-05-25 12:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranaction_date', models.DateField()),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('filled', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comission', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions', to=settings.AUTH_USER_MODEL)),
                ('comission_toke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissions', to='portfolio.Token')),
                ('first_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_fst', to='portfolio.Token')),
                ('second_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_snd', to='portfolio.Token')),
            ],
        ),
    ]
