# Generated by Django 2.2.19 on 2022-05-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='comission_toke',
            new_name='comission_token',
        ),
    ]
