# Generated by Django 2.2.19 on 2022-05-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220525_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Токен', 'verbose_name_plural': 'Токены'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='filled',
            new_name='amount',
        ),
    ]
