# Generated by Django 2.2.19 on 2022-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220526_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
