# Generated by Django 2.2.19 on 2022-05-26 17:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0011_auto_20220526_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranaction_date', models.DateTimeField()),
                ('first_coin', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Etherium'), ('USDT', 'Tether')], max_length=50)),
                ('second_coin', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Etherium'), ('USDT', 'Tether')], max_length=50)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comission', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comission_token', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Etherium'), ('USDT', 'Tether')], max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-tranaction_date'],
            },
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
