# Generated by Django 2.2.19 on 2022-05-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20220527_0753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('name', 'ticker')},
        ),
    ]
