# Generated by Django 2.2.19 on 2022-05-27 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0017_auto_20220527_0756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('owner', 'coin')},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
    ]
