# Generated by Django 2.2.19 on 2022-05-27 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20220527_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество'),
        ),
    ]
