# Generated by Django 2.2.19 on 2022-05-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-trans_date'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
