# Generated by Django 2.2.19 on 2022-05-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20220527_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buy',
            new_name='buy_or_sell',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='buy_for',
            new_name='buy_or_sell_for',
        ),
    ]
