# Generated by Django 2.2.19 on 2022-05-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20220527_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='side',
            field=models.CharField(choices=[('Buy', 'BUY'), ('Sell', 'SELL')], default='BUY', max_length=4),
        ),
    ]
