# Generated by Django 2.2.19 on 2022-06-08 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20220527_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 17, 57, 36, 512839, tzinfo=utc)),
        ),
    ]
