# Generated by Django 2.2.19 on 2022-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20220608_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(),
        ),
    ]
