# Generated by Django 2.2.19 on 2022-06-10 08:01

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20220609_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(datetime.datetime(2022, 6, 10, 8, 1, 2, 200886, tzinfo=utc))]),
        ),
    ]
