# Generated by Django 2.2.19 on 2022-06-10 08:01

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20220610_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='slug',
            field=models.SlugField(default='slug', max_length=20, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(datetime.datetime(2022, 6, 10, 8, 1, 23, 796718, tzinfo=utc))]),
        ),
    ]
