# Generated by Django 2.2.19 on 2022-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20220610_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buy_or_sell_for',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(),
        ),
    ]
